# Generated by Django 3.0.5 on 2020-06-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
