# Generated by Django 3.0.5 on 2020-06-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_item_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgridvalue',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='leads.ItemGridParameter'),
        ),
    ]
