# Generated by Django 3.0.5 on 2020-06-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20200624_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemgridvalue',
            options={'ordering': ['-priority'], 'verbose_name': 'Значение параметра размерной сетки', 'verbose_name_plural': 'Значения параметра размерной сетки'},
        ),
        migrations.AddField(
            model_name='itemgridvalue',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
