# Generated by Django 3.0.5 on 2020-06-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20200625_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemgridvalue',
            options={'ordering': ['priority'], 'verbose_name': 'Значение параметра размерной сетки', 'verbose_name_plural': 'Значения параметра размерной сетки'},
        ),
    ]
