# Generated by Django 3.0.5 on 2020-06-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20200629_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, help_text='Можно написать здесь результат созвона', null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('r', 'Оформлен'), ('p', 'Оплачен'), ('s', 'Созвонились'), ('c', 'Завершен')], default='r', help_text='Оформлен - человек оформил заказ (требует оплаты налом);\n                                           Оплачен - человек уже оплатил безналом;\n                                           Созвонились - мы созвонились и договорились о встрече, если того требует способ доставки;\n                                           Завершен - Товар отдали, деньги получили, все довольны;\n                                           ', max_length=1, verbose_name='Статус заказа'),
        ),
    ]
