# Generated by Django 3.0.5 on 2020-07-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('r', 'Оформлен'), ('p', 'Оплачен'), ('s', 'Созвонились'), ('c', 'Завершен'), ('o', 'Отменен')], default='r', help_text='Оформлен - человек оформил заказ (требует оплаты налом);\n                                           Оплачен - человек уже оплатил безналом;\n                                           Созвонились - мы созвонились и договорились о встрече, если того требует способ доставки;\n                                           Завершен - Товар отдали, деньги получили, все довольны;\n                                           ', max_length=1, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Итоговая стоимость заказа'),
        ),
    ]
