# Generated by Django 3.0.5 on 2020-07-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_auto_20200703_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
