# Generated by Django 3.0.5 on 2020-07-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_auto_20200703_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={'ordering': ['priority'], 'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
    ]
