# Generated by Django 3.0.5 on 2020-07-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
