# Generated by Django 3.0.5 on 2020-07-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_promo_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='use_count',
            field=models.IntegerField(default=0),
        ),
    ]
