# Generated by Django 3.0.5 on 2020-07-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_order_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='use_count',
        ),
    ]
