# Generated by Django 3.0.5 on 2020-07-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_auto_20200710_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
